# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    links:
      - db
    ports:
      - "4000:4000"
    environment:
      PG_CONNECTION_STRING: "postgres://library:library@db:5432/library"
  db:
    build:
      context: ./db
    restart: always
    environment:
      POSTGRES_PASSWORD: library
      POSTGRES_USER: library
    ports:
      - "5432:5432"